on: [push]

jobs:
  mail_on_push:
  runs_on: ubuntu-latest
  steps:
    name: Send mail
    uses: dawidd6/action-send-mail@v3
    with:
      server_aadress: smpt.gmail.com
      server_port: 465
      username: ${{secrets.MAIL_USERNAME}}
      password: ${{secrets.MAIL_PASSWORD}}

    subject: Github commit ${{github.event.head_commit.message}}
    body: ${{github.repository}} ${{github.event.pusher.name}}
    to: jelizaveta05@gmail.com
    from: Github actions
